### ISSUE TITLE
Изменить логику постинга шоунотов в Телеграм

### ISSUE THREAD

**Issue by grayru** [radio-t/gitter-rt-bot#11]
Сейчас бот по аналогии с гиттером после сообщения со ссылкой постит excerpt страницы по ссылке в чат. Но Телеграм сам публикует превью ссылки и такое поведение бота создает мусор в чате.

В случае с шоунотами выглядит даже хуже, потому что сначала в чат присылается сообщение с заголовком статьи и ссылка, которая разворачивается телеграмом, а потом бот отдельно постит excerpt. 
![Снимок экрана 2020-01-26 в 11 20 44](https://user-images.githubusercontent.com/1035620/73133200-0f71a200-402e-11ea-9499-44d1b4681b1a.png)

Предлагаю:
1. Отключить перехват ссылок в чате для сообщений, присланных не ботом.
2. Шоуноты отправлять не с пользовательского аккаунта, а самим ботом в формате — 
title
excerpt
link.

**Comment by grayru** [comment]
В принципе, можно и excerpt отключить — Телеграм прекрасно справляется сам.

**Comment by umputun** [comment]
да, https://github.com/radio-t/gitter-rt-bot/pull/10 это и делает
