### ISSUE TITLE
Excerpt (uKeeper) бот пишет JSON в чат

### ISSUE THREAD

**Issue by chuhlomin** [radio-t/gitter-rt-bot#7]
<img width="664" alt="" src="https://user-images.githubusercontent.com/3620471/72226566-6e301980-3560-11ea-9e6d-59fd7d2c6ed8.png">

https://gitter.im/radio-t/chat?at=5e1a48a63254b6754c91079c

```
{"id":"nh0o-ugub-8cby","errors":[{"id":"nh0o-ugub-8cby","name":"notFoundError"}]}
```

**Comment by umputun** [comment]
#10 делает эту проблему более не актуальной
